name: CD to Staging

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Staging via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          port: ${{ secrets.STAGING_SSH_PORT }}
          script: |
            set -e
            cd /home/${{ secrets.STAGING_USER }}/gravitas
            git fetch --all
            git reset --hard origin/main
            docker compose pull || true
            docker compose up -d --build
            docker compose ps
